# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c69b09f50f44517fae23f3fe64663491ab6fa300728d84d7afaa2a77343d91996fb8bf9056148f8e578567ea3a9fee76e8944722834ba9aa7a25b5518bc5d0b

test:
  secret_key_base: dc17a1152fc6425364c910b25447386070e41693261fbfbc43163e19f5e9b5ce9b3167b0e0061b3873db74ec82f0d63625e95108e0a593c7af43c68a21953e16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
